

logging.file: logs/application.log
logging:
  level:
      org:
        springframework:
          web: DEBUG
        hibernate: ERROR
server:
  port: 8099
spring:
  datasource:
    url:  jdbc:h2:file:./h2/org2;DB_CLOSE_ON_EXIT=FALSE